### ISSUE TITLE
ValueError: Invalid JSON data returned from network!

### ISSUE THREAD

**Issue by MasoudGhr** [ReagentX/purple_air_api#101]
Hi, the error "ValueError: Invalid JSON data returned from network!" is not resolved with re-running and also removing the "cache.sqlite". Is there any other solution for this error?
Thanks

**Comment by ReagentX** [comment]
This is addressed [in the FAQ](https://github.com/ReagentX/purple_air_api/blob/develop/docs/faq.md#valueerror-invalid-json-data-returned-from-network).
