### ISSUE TITLE
ValueError: Invalid JSON data returned from network!

### ISSUE THREAD

**Issue by bmosley** [ReagentX/purple_air_api#24]
hitting a ValueError with JSON return:

reproduced with
```
from purpleair.network import SensorList
p = SensorList()
```

```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5999909 (char 5999908)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bmosley/code/py_aqi/env/lib/python3.8/site-packages/purpleair/network.py", line 23, in __init__
    self.get_all_data()
  File "/Users/bmosley/code/py_aqi/env/lib/python3.8/site-packages/purpleair/network.py", line 38, in get_all_data
    raise ValueError(
ValueError: Invalid JSON data returned from network!

```

**Comment by bmosley** [comment]
this worked earlier. network issue maybe? very cool library though. thanks for making this!

**Comment by ReagentX** [comment]
This is an issue where PurpleAir’s API returns invalid JSON so we cannot parse it. Usually this means a double quote char or some other delimiter is missing. There is nothing we can do, so I raise this `ValueError`.

The only fix is to try again or invalidate/delete the cache that `requests_cache` creates. If the invalid response is cached (it shouldn’t be), you can delete the cache by removing the `cache.sqlite` file it creates in the project’s root directory.
