### ISSUE TITLE
Missing Parent Problem

### ISSUE THREAD

**Issue by jackson-waschura** [ReagentX/purple_air_api#70]
I've run into the "Child 5843 lists parent 5842, but parent does not exist!" error and I read through the FAQ and found that deleting the `cache.sqlite` file might help, but unfortunately it did not. I also see that this is an issue on purpleair's side, not this program, but it entirely prevents SensorList from working while the issue persists. Would it be viable for SensorList to accept a flag that would tell it to ignore these kinds of mismatches when constructing the sensor network?

**Comment by ReagentX** [comment]
Yes, this package should more gracefully handle this failure. Hopefully it’s temporary and it resolves itself, but I will add some code to handle this case.

**Comment by ReagentX** [comment]
Is this bug still present?
