### ISSUE TITLE
Custom Time Range for get_historical

### ISSUE THREAD

**Issue by thomastu** [ReagentX/purple_air_api#71]
# Motivation

Currently, `get_historical` collects some number of weeks of data relative to "today".  There could be special events which would motivate collecting data from specific sensors on/around specific dates.  The following would support this use case:

- `Channel.get_historical` should support either a relative time frame, or a custom start and end period.
- The behavior on the custom periods should mimic any behaviors needed to respect API limits on thingspeak.  One approach might be to partition the date range into week long chunks.

Thank you for all your work on this wrapper, it has saved a lot of time.

**Comment by ReagentX** [comment]
It should be fairly trivial to parametrize the start date, so the user can provide an optional start date as well as the number of weeks to go back.

https://github.com/ReagentX/purple_air_api/blob/df0d7cdb109aea9c2e0b71e798cef3e52d8d6b50/purpleair/channel.py#L176-L179
