### ISSUE TITLE
Field names disagreement with the PurpleAir documentation

### ISSUE THREAD

**Issue by anomp** [ReagentX/purple_air_api#78]
The column names of the Dataframe disagree with the  [(documentation)](https://docs.google.com/document/d/15ijz94dXJ-YAZLi9iZ_RaBwrZ4KtYeCy08goGBwnbCU/edit?usp=sharing). The fields are actually referring to the column names until 20 Oktober 2019. For example, `PM1.0_CF_ATM_ug/m3` is actually `PM1.0_CF1_ug/m3` according to documentation and field5 of `PARENT_PRIMARY_COLS` is `RSSI` instead of `ADC`. 

https://github.com/ReagentX/purple_air_api/blob/031f7ccac5d4dd6dd33e9b5abf4bf3f40d73d7a2/purpleair/api_data.py#L20-L70

**Comment by ReagentX** [comment]
Thanks for the issue; update coming shortly.
