### ISSUE TITLE
Requests_cache

### ISSUE THREAD

**Issue by ogunjosam** [ReagentX/purple_air_api#81]
A new update in the package requests_cache  (https://github.com/reclosedev/requests-cache/blob/master/requests_cache/core.py) 
 is throwing up an error  "AttributeError: module 'requests_cache' has no attribute 'core'"

What is the workaround?

**Comment by ReagentX** [comment]
For now, pin that dependency an older version. I will push an update to fix this problem.

**Comment by ReagentX** [comment]
https://github.com/ReagentX/purple_air_api/blob/0339bd1c8f4c40a503dd7d36604d957b8e70a47f/purpleair/api_data.py#L10-L15

**Comment by ReagentX** [comment]
https://requests-cache.readthedocs.io/en/latest/user_guide.html#patching

**Comment by ReagentX** [comment]
To see the changes, reinstall the package in your `venv` or upgrade it manually with `pip install --upgrade purpleair`
