### ISSUE TITLE
Limit to Historical Data

### ISSUE THREAD

**Issue by callieclark** [ReagentX/purple_air_api#94]
I am trying to pull data for the first six months of 2020 for all of the Bay Area, and it appears that I am not able to query that far back. I checked with PurpleAir and the data should be accessible for that time period. Is there a restriction applied through this API that could be creating this issue? 

Thanks for the help!

**Comment by ReagentX** [comment]
Ostensibly if the data is in the API this library should retrieve it. Are you able to share the code you are using to request the relevant data?

**Comment by callieclark** [comment]
Actually, I found the issue. Looks like the majority of the sensors I was testing were fairly new (must be due to the wildfires) and the data actually did not exist. Thank you for the input!
